language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer self-update
  - composer install --prefer-source --no-interaction --optimize-autoloader

before_script:
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .

script:
  - ./vendor/bin/tester -s -j 32 -c ./tests/php.ini-unix ./tests/CronnerTests

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
