language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

env:
  - PHP_BIN=php
  - PHP_BIN=php-cgi

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: hhvm-nightly

  exclude:
    - php: hhvm
      env: PHP_BIN=php-cgi

    - php: hhvm-nightly
      env: PHP_BIN=php-cgi

install:
  - composer self-update
  - composer install --prefer-source --no-interaction --optimize-autoloader

before_script:
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .

script:
  - ./vendor/bin/tester -s -p $PHP_BIN -j 32 -c ./tests/php.ini-unix ./tests/CronnerTests

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
